### ISSUE TITLE
Backlog and sprint board are empty

### ISSUE THREAD

**Issue by ghost** [256MbTeam/Redmine-Scrumbler#40]
Redmine 1.3 (using the ppa package on ubuntu 11.04) on sqlite

Code for the expected issues is generated:

```
<div id='dashboard_for_sprint_2' style='width:100%;height=100%;'>&nbsp;</div><script type="text/javascript">
```

//<![CDATA[
new Scrumbler.ScrumblerDashboard('dashboard_for_sprint_2', {"issues":[{"assigned_to":{"name":"Michael Utech","id":3},"project_id":1,"subject":"Setup issue tracking and project planing tool","closed":false,"points":"20","tracker_id":3,"id":2,"status_id":1}],"statuses":{"5":{"use":"true","name":"Closed","closed":true,"status_id":5,"position":"5"},"6":{"use":"true","name":"Rejected","closed":true,"status_id":6,"position":"6"},"1":{"use":"true","name":"New","closed":false,"status_id":1,"position":"1"},"2":{"use":"true","name":"In Progress","closed":false,"status_id":2,"position":"2"},"3":{"use":"true","name":"Resolved","closed":false,"status_id":3,"position":"3"},"4":{"use":"true","name":"Feedback","closed":false,"status_id":4,"position":"4"}},"current_user_id":3,"sprint":{"version_id":2,"id":2,"fact_close_date":null,"project_id":1,"start_date":"2012/02/25","max_points":100,"settings":{"trackers":{"2":{"use":"true","color":"afa","position":"3"},"1":{"use":"true","color":"faa","position":"2"},"3":{"use":"true","color":"aaf","position":"4"},"5":{"use":"true","color":"","position":"1"}},"issue_statuses":{"6":{"use":"true","position":"6"},"5":{"use":"true","position":"5"},"4":{"use":"true","position":"4"},"3":{"use":"true","position":"3"},"2":{"use":"true","position":"2"},"1":{"use":"true","position":"1"}}},"name":"Kickoff for the final prototype","status":"opened"},"name":"Kickoff for the final prototype","url":"https://dev.","trackers":{"5":{"use":"true","name":"Infrastructure","color":"","position":"1"},"1":{"use":"true","name":"Bug","color":"faa","position":"2"},"2":{"use":"true","name":"Feature","color":"afa","position":"3"},"3":{"use":"true","name":"Support","color":"aaf","position":"4"}},"project":{"updated_on":"2012/02/26 12:47:27 +0100","id":1,"parent_id":null,"homepage":"","is_public":true,"identifier":"xodlprototype","description":"The prototype resulting from the development on Aka.Commons.DataTypes and Softwed.Una","created_on":"2012/02/26 12:47:27 +0100","rgt":2,"name":"XODL Technology Prototype","status":1,"lft":1}});
//]]>
</script>

but not displayed.

**Comment by snicke** [comment]
Can confirm this bug.

**Comment by zloydadka** [comment]
what browser do you use?

**Comment by snicke** [comment]
Chrome, Firefox and IE

**Comment by zloydadka** [comment]
fixed
try lastest version from ee17d82@master

**Comment by ghost** [comment]
I still don't see anything, not in the sprint view, neither in the backlog
